package com.turkcell.order_service.domain.enums;

public enum SagaStep {
    ORDER_CREATED,
    PAYMENT_PENDING,
    PAYMENT_COMPLETED,
    SUBSCRIPTION_ACTIVATION_PENDING,
    SUBSCRIPTION_ACTIVATED,
    ORDER_FULFILLED,
    COMPENSATION_STARTED,
    ORDER_CANCELLED
}
