server:
  port: 9009

spring:
  application:
    name: notification-service
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/telco-crm
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    schemas: notification_service
    default-schema: notification_service
    baseline-on-migrate: true
