<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.turkcell.telcocrm</groupId>
    <artifactId>turkcell-telco-crm-microservices</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <packaging>pom</packaging>

    <modules>
        <module>customer-service</module>
        <module>product-catalog-service</module>
        <module>order-service</module>
        <module>subscription-service</module>
        <module>usage-service</module>
        <module>billing-service</module>
        <module>payment-service</module>
        <module>notification-service</module>
        <module>ticket-service</module>
    </modules>

</project>