ALTER TABLE usage_service.quotas
    ADD COLUMN IF NOT EXISTS customer_id UUID,
    ADD COLUMN IF NOT EXISTS minutes_total INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS sms_total INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS mb_total INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS voice_used INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS sms_used INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS data_mb_used INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS overage_voice_minutes INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS overage_sms INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS overage_data_mb INT NOT NULL DEFAULT 0;
