server:
  port: 9008

spring:
  application:
    name: payment-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    default-schema: payment_service
    schemas: payment_service

payment:
  gateway:
    success-rate: 0.8
  retry:
    delay-hours:
      - 24
      - 72
      - 168
    use-minutes-for-dev: true
