spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ayminacakir/turkcell-telco-crm-microservices.git
          default-label: aymina
          search-paths: configs,configs/{application}
          clone-on-start: true
          force-pull: true

server:
  port: 8888
