server:
  port: 9007

spring:
  application:
    name: billing-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: billing-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    default-schema: billing_service
    schemas: billing_service
