spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/telco-crm
  cloud:
    gateway:
      mvc:
        routes:
          - id: customer-service
            uri: lb://customer-service
            predicates:
              - Path=/api/v1/customers/**
          - id: order-service
            uri: lb://order-service
            predicates:
              - Path=/api/v1/orders/**
          - id: subscription-service
            uri: lb://subscription-service
            predicates:
              - Path=/api/v1/subscriptions/**
          - id: billing-service
            uri: lb://billing-service
            predicates:
              - Path=/api/v1/billing/**
          - id: payment-service
            uri: lb://payment-service
            predicates:
              - Path=/api/v1/payments/**
