spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: customer-service
              uri: lb://customer-service
              predicates:
                - Path=/api/v1/customers/**
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/v1/orders/**
            - id: subscription-service
              uri: lb://subscription-service
              predicates:
                - Path=/api/v1/subscriptions/**
