server:
  port: 9006

spring:
  application:
    name: usage-service
  datasource:
    url: jdbc:postgresql://localhost:5436/usage_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true