server:
  port: 9010

spring:
  application:
    name: ticket-service
  datasource:
    url: jdbc:postgresql://localhost:5440/ticket_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true