server:
  port: 9003

spring:
  application:
    name: product-catalog-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    schemas: product_catalog_service
    default-schema: product_catalog_service
    baseline-on-migrate: true
